import { useState, useEffect } from 'react';

export const corbQuestions: any[] = [

  // 90s WRESTLING
  { text:"What was Steve Austin's catchphrase that defined the Attitude Era?", answers:["Can you smell what I'm cookin'?","And that's the bottom line...","Whatcha gonna do?","Oh yeah!"], correct:1 },
  { text:"Which two wrestlers did WCW sign from WWF to kick off the Monday Night Wars?", answers:["Razor Ramon & Diesel","The Undertaker & Mankind","The Hardy Boyz","Demolition"], correct:0 },
  { text:"What year did the nWo debut in WCW?", answers:["1994","1995","1996","1997"], correct:2 },
  { text:"Who were the original three members of the nWo?", answers:["Hogan, Nash, Hall","Hogan, Savage, Piper","Hall, Nash, Luger","Hogan, Hall, Sting"], correct:0 },
  { text:"What was Mick Foley's most beloved alter ego besides Mankind?", answers:["Dude Love","Cactus Jack","Both A and B","Mr. Socko"], correct:2 },
  { text:"The Montreal Screwjob in 1997 involved which two wrestlers?", answers:["Austin vs. Hart","Bret Hart vs. Shawn Michaels","Goldberg vs. Hogan","Mankind vs. Undertaker"], correct:1 },
  { text:"What was DX's most famous catchphrase?", answers:["Suck it!","Talk to the hand","Are you ready?","Break it down!"], correct:0 },
  { text:"Which PPV featured Mankind being thrown off the top of Hell in a Cell?", answers:["Summerslam 1998","Royal Rumble 1998","King of the Ring 1998","Survivor Series 1998"], correct:2 },
  { text:"Who was known as 'The Heartbreak Kid' in the WWF?", answers:["Triple H","Shawn Michaels","Razor Ramon","1-2-3 Kid"], correct:1 },
  { text:"Goldberg's undefeated streak in WCW ended at how many wins?", answers:["100","137","173","212"], correct:2 },
  { text:"What finishing move did Diamond Dallas Page use?", answers:["Diamond Cutter","People's Elbow","Sweet Chin Music","Clothesline from Hell"], correct:0 },
  { text:"Who defeated Goldberg to end his undefeated streak with help from a taser?", answers:["Sting","Hogan","Kevin Nash","Scott Steiner"], correct:2 },
  { text:"The Rock's finishing moves included which of these?", answers:["Rock Bottom only","People's Elbow only","Both Rock Bottom and People's Elbow","Spinebuster"], correct:2 },
  { text:"Which tag team was known as 'The Road Warriors' in the 90s?", answers:["The Dudley Boyz","Legion of Doom","The Hardy Boyz","The New Age Outlaws"], correct:1 },
  { text:"What was The Undertaker's signature finishing move?", answers:["Tombstone Piledriver","Last Ride","Chokeslam","Dead Man Drop"], correct:0 },
  { text:"Sting's late 90s look was inspired by which movie character?", answers:["Joker","The Crow","Phantom of the Opera","Batman"], correct:1 },
  { text:"What year did Steve Austin win his first WWF Championship?", answers:["1996","1997","1998","1999"], correct:2 },
  { text:"Which WWF tag team were known as 'The Rockers'?", answers:["Shawn Michaels & Marty Jannetty","Edge & Christian","Too Cool","LOD"], correct:0 },
  { text:"What was the name of the WCW show that competed with WWF Raw on Monday nights?", answers:["WCW Saturday Night","WCW Nitro","WCW Thunder","WCW Main Event"], correct:1 },
  { text:"Which wrestler was nicknamed 'The Excellence of Execution'?", answers:["Shawn Michaels","Bret Hart","Chris Jericho","Owen Hart"], correct:1 },

  // SIDNEY SWEENEY
  { text:"What HBO series made Sidney Sweeney a household name?", answers:["Succession","Euphoria","White Lotus","Big Little Lies"], correct:1 },
  { text:"What character does Sidney Sweeney play in Euphoria?", answers:["Rue","Maddy","Cassie Howard","Kat"], correct:2 },
  { text:"Sidney Sweeney appeared in which season of The White Lotus?", answers:["Season 1","Season 2","Season 3","She wasn't in White Lotus"], correct:1 },
  { text:"What state is Sidney Sweeney originally from?", answers:["California","Texas","Washington","Oregon"], correct:2 },
  { text:"Sidney Sweeney starred alongside Glen Powell in which 2024 rom-com?", answers:["Anyone But You","No Hard Feelings","The Idea of You","Set It Up"], correct:0 },
  { text:"What Marvel character did Sidney Sweeney play in a 2024 film?", answers:["Spider-Woman","Madame Web","Cassandra Webb","Black Cat"], correct:2 },
  { text:"What streaming service airs Euphoria?", answers:["Netflix","Hulu","HBO/Max","Amazon Prime"], correct:2 },
  { text:"In The White Lotus Season 2, where is the show set?", answers:["Hawaii","Sicily, Italy","Thailand","Mexico"], correct:1 },
  { text:"Sidney Sweeney played a nun in which 2024 horror film?", answers:["Immaculate","Consecration","The Nun III","Saint Maud"], correct:0 },
  { text:"Sidney Sweeney is known for restoring what type of vehicle as a hobby?", answers:["Motorcycles","Vintage cars","Boats","Tractors"], correct:1 },
  { text:"What thriller did Sidney Sweeney star in alongside Justice Smith in 2021?", answers:["The Voyeurs","Nocturne","Sharp Stick","The Thing About Pam"], correct:0 },
  { text:"Sidney Sweeney also worked as a producer on which project?", answers:["Reality","Euphoria Season 2","Anyone But You","The Voyeurs"], correct:0 },
  { text:"What sport does Cassie love in Euphoria?", answers:["Gymnastics","Ice skating","Cheerleading","Swimming"], correct:1 },
  { text:"Sidney Sweeney studied what subject in college?", answers:["Film","Business","Pre-med","Communications"], correct:2 },
  { text:"Which major magazine did Sidney Sweeney cover multiple times in 2023?", answers:["Vogue","Vanity Fair","Rolling Stone","Elle"], correct:0 },

  // THE HOUSEMAID
  { text:"The Housemaid starring Sidney Sweeney is based on a novel by which author?", answers:["Gillian Flynn","Freida McFadden","Lisa Jewell","Liane Moriarty"], correct:1 },
  { text:"What streaming platform released The Housemaid film?", answers:["Netflix","Amazon Prime","Apple TV+","Max"], correct:0 },
  { text:"What is the name of Sidney Sweeney's character in The Housemaid?", answers:["Nina","Millie","Rachel","Claire"], correct:1 },
  { text:"What genre best describes The Housemaid?", answers:["Romantic comedy","Psychological thriller","Action drama","Sci-fi mystery"], correct:1 },
  { text:"The Housemaid novel became a massive hit through which platform?", answers:["Audiobook","BookTok/TikTok","Serialized podcast","Graphic novel"], correct:1 },
  { text:"What is the sequel to The Housemaid novel called?", answers:["The Housemaid Returns","The Housemaid's Secret","The New Housemaid","The Servant"], correct:1 },
  { text:"Freida McFadden, author of The Housemaid, is also a practicing what?", answers:["Lawyer","Physician","Professor","Journalist"], correct:1 },
  { text:"Who plays the husband Andrew in The Housemaid film?", answers:["Austin Butler","Brandon Sklenar","Glen Powell","Jacob Elordi"], correct:1 },
  { text:"What year was The Housemaid novel first published?", answers:["2019","2020","2021","2022"], correct:2 },
  { text:"The Housemaid is set primarily inside what kind of location?", answers:["A city apartment","A remote island","A large private estate","A small-town inn"], correct:2 },
  { text:"What major plot device drives The Housemaid story?", answers:["The husband is a spy","The maid has a hidden past","The house is haunted","The wife faked her death"], correct:1 },
  { text:"What job does Millie take in The Housemaid?", answers:["Nanny","Chef","Housekeeper","Personal assistant"], correct:2 },
  { text:"The Housemaid film was directed by whom?", answers:["Ari Aster","Mike Flanagan","Paul Feig","Alex Kalymnios"], correct:3 },
  { text:"What type of wealthy household does Millie enter in The Housemaid?", answers:["A tech mogul's family","A troubled marriage in a mansion","A politician's household","A celebrity couple"], correct:1 },
  { text:"Amanda Brugel plays what role in The Housemaid film?", answers:["The previous housekeeper","Nina the wife","A detective","The grandmother"], correct:0 },

  // MONSTER SQUAD
  { text:"What year was The Monster Squad released?", answers:["1985","1986","1987","1988"], correct:2 },
  { text:"Who directed The Monster Squad?", answers:["John Carpenter","Wes Craven","Fred Dekker","Joe Dante"], correct:2 },
  { text:"Which classic monsters appear in The Monster Squad?", answers:["Dracula, Frankenstein, Wolfman, Mummy, Gill-man","Dracula, Freddy, Jason, Michael Myers","Frankenstein, King Kong, The Blob","Dracula, Wolfman, The Creature"], correct:0 },
  { text:"The Monster Squad is often compared to which other 80s kids adventure film?", answers:["E.T.","The Goonies","Stand By Me","Gremlins"], correct:1 },
  { text:"Who delivers the iconic line 'Wolfman's got nards!'?", answers:["Sean","Horace (Fat Kid)","Rudy","Eugene"], correct:1 },
  { text:"Who co-wrote the Monster Squad screenplay alongside director Fred Dekker?", answers:["Stephen King","Shane Black","John Hughes","Richard Donner"], correct:1 },
  { text:"What rating did The Monster Squad receive?", answers:["G","PG","PG-13","R"], correct:2 },
  { text:"Monster Squad flopped at the box office but found its audience through what?", answers:["Netflix revival","VHS and cable TV","Theatrical re-release","Sequel hype"], correct:1 },
  { text:"Which actor played Dracula in The Monster Squad?", answers:["Christopher Lee","Duncan Regehr","Frank Langella","Gary Oldman"], correct:1 },
  { text:"What is the name of the creepy old man who helps the kids in Monster Squad?", answers:["Professor Abner","Scary German Guy","Old Man Rupert","Van Helsing Jr."], correct:1 },
  { text:"What artifact do the kids need to defeat Dracula in Monster Squad?", answers:["A silver bullet","Van Helsing's diary and an amulet","Holy water","A wooden stake"], correct:1 },
  { text:"Which monster has a sympathetic side in The Monster Squad?", answers:["Dracula","Frankenstein's Monster","The Mummy","The Gill-man"], correct:1 },
  { text:"Monster Squad is set in what kind of American town?", answers:["A remote rural farm town","A typical suburban town","A coastal beach town","An urban city"], correct:1 },
  { text:"What is Monster Squad's climax centered around?", answers:["A portal to send monsters to limbo","Destroying Dracula's castle","A silver bullet showdown","A government raid"], correct:0 },
  { text:"What year is The Monster Squad set in?", answers:["1950s","1960s","Contemporary 1980s","1970s"], correct:2 },

  // EAST PITTSBURGH HISTORY
  { text:"East Pittsburgh is located in which Pennsylvania county?", answers:["Westmoreland","Allegheny","Butler","Washington"], correct:1 },
  { text:"What major company had its enormous works in East Pittsburgh?", answers:["U.S. Steel","Carnegie Steel","Westinghouse Electric","Alcoa"], correct:2 },
  { text:"Westinghouse's East Pittsburgh works were known for manufacturing what?", answers:["Automobiles","Electrical generators and turbines","Glass","Textiles"], correct:1 },
  { text:"KDKA, one of the first commercial radio stations in the US, is associated with which company based near East Pittsburgh?", answers:["Carnegie Steel","Westinghouse","Alcoa","PPG"], correct:1 },
  { text:"What river valley runs through the East Pittsburgh area?", answers:["Ohio River","Allegheny River","Monongahela River","Turtle Creek"], correct:3 },
  { text:"At their peak the Westinghouse East Pittsburgh works employed roughly how many workers?", answers:["2,000","10,000","20,000","50,000"], correct:2 },
  { text:"George Westinghouse is famous for developing what alongside his East Pittsburgh works?", answers:["The steam engine","AC electrical power and air brakes","The telephone","The automobile"], correct:1 },
  { text:"East Pittsburgh is close to which historically significant steel town?", answers:["Johnstown","Braddock","Aliquippa","Clairton"], correct:1 },
  { text:"The 15112 zip code covers which borough?", answers:["Braddock","East Pittsburgh","Rankin","Edgewood"], correct:1 },
  { text:"What major highway runs through the East Pittsburgh / Turtle Creek valley area?", answers:["I-376 Parkway East","I-79","Route 30","I-279"], correct:0 },
  { text:"The Westinghouse Bridge near East Pittsburgh once held what record?", answers:["Longest suspension bridge","Longest concrete arch bridge in the world","Highest bridge in Pennsylvania","Oldest bridge in Allegheny County"], correct:1 },
  { text:"The Westinghouse Bridge spans which waterway?", answers:["Monongahela River","Turtle Creek valley","Allegheny River","Chartiers Creek"], correct:1 },
  { text:"The decline of which industry devastated East Pittsburgh in the 1970s-80s?", answers:["Coal","Steel and heavy manufacturing","Textiles","Agriculture"], correct:1 },
  { text:"East Pittsburgh was incorporated as a borough in what decade?", answers:["1870s","1880s","1890s","1900s"], correct:2 },
  { text:"The area around East Pittsburgh was part of which early American frontier conflict zone?", answers:["War of 1812 frontier","French and Indian War territory","Civil War border region","Revolutionary War battleground"], correct:1 },
  { text:"What transit authority connects East Pittsburgh to the greater Pittsburgh region?", answers:["SEPTA","Pittsburgh Regional Transit","Westmoreland Transit","Metro Pittsburgh"], correct:1 },
  { text:"East Pittsburgh neighbors which borough to the west?", answers:["Wilkinsburg","Edgewood","Swissvale","Braddock"], correct:0 },
  { text:"The 'Electric Valley' nickname for the East Pittsburgh corridor refers to whose legacy?", answers:["Carnegie Steel","Westinghouse Electric","Alcoa","U.S. Steel"], correct:1 },
  { text:"Which famous fort was located at the forks of the Ohio near Pittsburgh during the French and Indian War?", answers:["Fort Necessity","Fort Ligonier","Fort Pitt","Fort Bedford"], correct:2 },
  { text:"What catastrophic 1892 labor battle took place just west of Westmoreland County at a steel mill?", answers:["Pullman Strike","Homestead Strike","Coal Strike of 1902","McKees Rocks Strike"], correct:1 },

  // CHARLES BARKLEY
  { text:"What nickname is Charles Barkley most famous for?", answers:["The Round Mound of Rebound","Sir Charles","Both A and B","Chuck the Truck"], correct:2 },
  { text:"Charles Barkley played college basketball at which university?", answers:["Alabama","Auburn","LSU","Georgia"], correct:1 },
  { text:"What year did Charles Barkley win the NBA MVP award?", answers:["1991","1993","1995","1997"], correct:1 },
  { text:"Charles Barkley was drafted by which NBA team in 1984?", answers:["Houston Rockets","Phoenix Suns","Philadelphia 76ers","Chicago Bulls"], correct:2 },
  { text:"Barkley's famous Nike commercial declared 'I am not a ___.'", answers:["Criminal","Role model","Cheater","Loser"], correct:1 },
  { text:"Who was NOT on the 1992 Dream Team with Barkley?", answers:["Michael Jordan","Magic Johnson","Kobe Bryant","Larry Bird"], correct:2 },
  { text:"Charles Barkley reached the NBA Finals once — with which team?", answers:["Philadelphia 76ers","Houston Rockets","Phoenix Suns","He never reached the Finals"], correct:2 },
  { text:"Who did the Phoenix Suns lose to in the 1993 NBA Finals?", answers:["Chicago Bulls","Houston Rockets","Utah Jazz","New York Knicks"], correct:0 },
  { text:"Charles Barkley is a longtime co-host of which TV sports show?", answers:["SportsCenter","Inside the NBA on TNT","First Take","PTI"], correct:1 },
  { text:"What is Charles Barkley's home state?", answers:["Georgia","Mississippi","Alabama","Tennessee"], correct:2 },
  { text:"Charles Barkley was inducted into the Basketball Hall of Fame in what year?", answers:["2000","2004","2006","2008"], correct:2 },
  { text:"What word does Shaquille O'Neal use to mock Barkley's predictions on Inside the NBA?", answers:["Horrible","Turrible","Awful","Wrong"], correct:1 },
  { text:"Barkley famously feuded playfully with which fellow TNT analyst?", answers:["Kenny Smith","Shaquille O'Neal","Ernie Johnson","All of the above"], correct:3 },
  { text:"Despite being listed at 6'4\", Barkley's height was often considered what?", answers:["Accurate","Inflated by 2 inches","Shortened by 2 inches","Exactly average for a PF"], correct:1 },
  { text:"Charles Barkley's position was power forward. What made him unusual for the position?", answers:["He was too tall","He was undersized at around 6'4\" but dominated rebounding","He never dunked","He played point guard in college"], correct:1 },

];