export const easyQuestions: any[] = [
  { cat:'Pop Culture', difficulty:'easy', text:'Which singer is known as the "Material Girl"?', answers:['Madonna','Cher','Cyndi Lauper','Whitney Houston'], correct:0 },
  { cat:'Pop Culture', difficulty:'easy', text:'What is the name of Mickey Mouse\'s dog?', answers:['Pluto','Goofy','Max','Scooby'], correct:0 },
  { cat:'Pop Culture', difficulty:'easy', text:'Which superhero is also known as Bruce Wayne?', answers:['Batman','Superman','Iron Man','Spider-Man'], correct:0 },
  { cat:'Pop Culture', difficulty:'easy', text:'What color pill does Neo take in The Matrix?', answers:['Blue','Red','Green','Yellow'], correct:1 },
  { cat:'Pop Culture', difficulty:'easy', text:'Which princess loses a glass slipper?', answers:['Cinderella','Ariel','Belle','Jasmine'], correct:0 },
  { cat:'Pop Culture', difficulty:'easy', text:'Who lives in a pineapple under the sea?', answers:['Patrick Star','SpongeBob SquarePants','Squidward','Mr. Krabs'], correct:1 },
  { cat:'Pop Culture', difficulty:'easy', text:'Which movie features the song "Let It Go"?', answers:['Tangled','Frozen','Moana','Encanto'], correct:1 },
  { cat:'Pop Culture', difficulty:'easy', text:'What is the name of Harry Potter\'s owl?', answers:['Crookshanks','Scabbers','Hedwig','Fawkes'], correct:2 },
  { cat:'Pop Culture', difficulty:'easy', text:'Which artist sang "Thriller"?', answers:['Prince','Michael Jackson','Usher','Justin Timberlake'], correct:1 },
  { cat:'Pop Culture', difficulty:'easy', text:'What toy cowboy is a main character in Toy Story?', answers:['Buzz Lightyear','Woody','Rex','Slinky Dog'], correct:1 },
  { cat:'Pop Culture', difficulty:'easy', text:'Which TV family lives at 742 Evergreen Terrace?', answers:['The Griffins','The Simpsons','The Belchers','The Browns'], correct:1 },
  { cat:'Pop Culture', difficulty:'easy', text:'What is the name of Elsa\'s sister in Frozen?', answers:['Anna','Olaf','Kristoff','Sven'], correct:0 },
  { cat:'Pop Culture', difficulty:'easy', text:'Which actor played Jack in Titanic?', answers:['Brad Pitt','Tom Cruise','Leonardo DiCaprio','Matt Damon'], correct:2 },
  { cat:'Pop Culture', difficulty:'easy', text:'What kind of animal is Pikachu?', answers:['Cat','Rabbit','Mouse','Fox'], correct:2 },
  { cat:'Pop Culture', difficulty:'easy', text:'Which singer performed "Shake It Off"?', answers:['Taylor Swift','Adele','Katy Perry','Lady Gaga'], correct:0 },
  { cat:'Pop Culture', difficulty:'easy', text:'What city is Batman commonly associated with?', answers:['Metropolis','Gotham City','Star City','Central City'], correct:1 },
  { cat:'Pop Culture', difficulty:'easy', text:'Who is Shrek\'s wife?', answers:['Fiona','Rapunzel','Merida','Tiana'], correct:0 },
  { cat:'Pop Culture', difficulty:'easy', text:'Which streaming service created Stranger Things?', answers:['Hulu','Prime Video','Netflix','Disney+'], correct:2 },
  { cat:'Pop Culture', difficulty:'easy', text:'What instrument does Lisa Simpson play?', answers:['Saxophone','Violin','Piano','Drums'], correct:0 },
  { cat:'Pop Culture', difficulty:'easy', text:'Which movie features a clownfish named Nemo?', answers:['Finding Nemo','Shark Tale','Cars','Up'], correct:0 },
  { cat:'Sports', difficulty:'easy', text:'How many points is a touchdown worth in football before the extra point?', answers:['3','6','7','8'], correct:1 },
  { cat:'Sports', difficulty:'easy', text:'What sport uses a bat, ball, and bases?', answers:['Soccer','Baseball','Hockey','Tennis'], correct:1 },
  { cat:'Sports', difficulty:'easy', text:'In basketball, how many points is a free throw worth?', answers:['1','2','3','4'], correct:0 },
  { cat:'Sports', difficulty:'easy', text:'What country is famous for the sport of sumo wrestling?', answers:['China','South Korea','Japan','Thailand'], correct:2 },
  { cat:'Sports', difficulty:'easy', text:'How many players are on the field for one soccer team during play?', answers:['9','10','11','12'], correct:2 },
  { cat:'Sports', difficulty:'easy', text:'What sport is known as "America\'s pastime"?', answers:['Football','Basketball','Baseball','Golf'], correct:2 },
  { cat:'Sports', difficulty:'easy', text:'Which sport uses terms like birdie, bogey, and par?', answers:['Tennis','Golf','Soccer','Bowling'], correct:1 },
  { cat:'Sports', difficulty:'easy', text:'How many rings are on the Olympic flag?', answers:['4','5','6','7'], correct:1 },
  { cat:'Sports', difficulty:'easy', text:'Which sport uses a puck?', answers:['Lacrosse','Field Hockey','Ice Hockey','Rugby'], correct:2 },
  { cat:'Sports', difficulty:'easy', text:'What is the maximum score in a single frame of bowling?', answers:['20','30','40','50'], correct:1 },
  { cat:'Sports', difficulty:'easy', text:'Which famous athlete is nicknamed "King James"?', answers:['Kobe Bryant','Michael Jordan','LeBron James','Kevin Durant'], correct:2 },
  { cat:'Sports', difficulty:'easy', text:'In tennis, what is the term for a score of zero?', answers:['Blank','Love','Nil','Zip'], correct:1 },
  { cat:'Sports', difficulty:'easy', text:'What color card means a player is sent off in soccer?', answers:['Blue','Green','Yellow','Red'], correct:3 },
  { cat:'Sports', difficulty:'easy', text:'How many holes are played in a standard round of golf?', answers:['9','12','18','27'], correct:2 },
  { cat:'Sports', difficulty:'easy', text:'What sport did Michael Jordan play professionally?', answers:['Baseball','Basketball','Football','Golf'], correct:1 },
  { cat:'Sports', difficulty:'easy', text:'Which sport features the Tour de France?', answers:['Running','Swimming','Cycling','Skiing'], correct:2 },
  { cat:'Sports', difficulty:'easy', text:'What piece in chess can move in an L-shape?', answers:['Bishop','Knight','Rook','Queen'], correct:1 },
  { cat:'Sports', difficulty:'easy', text:'How many points is a three-pointer worth in basketball?', answers:['2','3','4','5'], correct:1 },
  { cat:'Sports', difficulty:'easy', text:'What sport does Serena Williams play?', answers:['Gymnastics','Tennis','Soccer','Track'], correct:1 },
  { cat:'Sports', difficulty:'easy', text:'Which sport includes the Super Bowl?', answers:['Basketball','Baseball','Football','Hockey'], correct:2 },
  { cat:'History', difficulty:'easy', text:'Who was the first President of the United States?', answers:['Thomas Jefferson','George Washington','Abraham Lincoln','John Adams'], correct:1 },
  { cat:'History', difficulty:'easy', text:'Which ancient civilization built the pyramids?', answers:['Romans','Greeks','Egyptians','Mayans'], correct:2 },
  { cat:'History', difficulty:'easy', text:'In which country did the Renaissance begin?', answers:['France','Italy','Spain','Germany'], correct:1 },
  { cat:'History', difficulty:'easy', text:'What wall fell in 1989, symbolizing the end of the Cold War?', answers:['Great Wall','Berlin Wall','Hadrian\'s Wall','Wailing Wall'], correct:1 },
  { cat:'History', difficulty:'easy', text:'Who discovered America in 1492 according to popular history lessons?', answers:['Ferdinand Magellan','Christopher Columbus','Marco Polo','Amerigo Vespucci'], correct:1 },
  { cat:'History', difficulty:'easy', text:'Which ship sank after hitting an iceberg in 1912?', answers:['Lusitania','Britannic','Titanic','Mayflower'], correct:2 },
  { cat:'History', difficulty:'easy', text:'Who was known as the Maid of Orléans?', answers:['Marie Antoinette','Joan of Arc','Catherine de Medici','Eleanor of Aquitaine'], correct:1 },
  { cat:'History', difficulty:'easy', text:'Which U.S. president issued the Emancipation Proclamation?', answers:['George Washington','Abraham Lincoln','Theodore Roosevelt','Woodrow Wilson'], correct:1 },
  { cat:'History', difficulty:'easy', text:'What empire was ruled by Julius Caesar?', answers:['Greek Empire','Roman Republic','Roman Empire','Ottoman Empire'], correct:2 },
  { cat:'History', difficulty:'easy', text:'Which war was fought between the North and South regions of the United States?', answers:['World War I','Revolutionary War','Civil War','War of 1812'], correct:2 },
  { cat:'History', difficulty:'easy', text:'Who was the British queen with the longest reign before Charles III?', answers:['Queen Victoria','Queen Elizabeth II','Queen Mary','Queen Anne'], correct:1 },
  { cat:'History', difficulty:'easy', text:'What was the name of the trade route linking China and the West?', answers:['Spice Road','Royal Road','Silk Road','Amber Road'], correct:2 },
  { cat:'History', difficulty:'easy', text:'Which famous speech begins with "I have a dream"?', answers:['Gettysburg Address','We Shall Fight on the Beaches','I Have a Dream','Four Freedoms'], correct:2 },
  { cat:'History', difficulty:'easy', text:'What document begins with "We the People"?', answers:['Bill of Rights','Magna Carta','U.S. Constitution','Declaration of Independence'], correct:2 },
  { cat:'History', difficulty:'easy', text:'Who was the first man to walk on the moon?', answers:['Buzz Aldrin','Yuri Gagarin','Neil Armstrong','John Glenn'], correct:2 },
  { cat:'History', difficulty:'easy', text:'What year did World War II end?', answers:['1943','1944','1945','1946'], correct:2 },
  { cat:'History', difficulty:'easy', text:'Who was famous for the phrase "Let them eat cake," though likely misattributed?', answers:['Joan of Arc','Marie Antoinette','Queen Elizabeth I','Catherine the Great'], correct:1 },
  { cat:'History', difficulty:'easy', text:'Which explorer led the first expedition to circumnavigate the globe?', answers:['Columbus','Magellan','Cook','Drake'], correct:1 },
  { cat:'History', difficulty:'easy', text:'What civilization is associated with Machu Picchu?', answers:['Aztec','Maya','Inca','Olmec'], correct:2 },
  { cat:'History', difficulty:'easy', text:'Which famous leader was known for his short stature and military success in France?', answers:['Napoleon Bonaparte','Louis XIV','Charlemagne','Robespierre'], correct:0 },
  { cat:'Food', difficulty:'easy', text:'What fruit is commonly mistaken for a vegetable and used in ketchup?', answers:['Tomato','Apple','Pepper','Carrot'], correct:0 },
  { cat:'Food', difficulty:'easy', text:'Which food is made from curdled milk?', answers:['Bread','Cheese','Rice','Pasta'], correct:1 },
  { cat:'Food', difficulty:'easy', text:'What is sushi traditionally wrapped in?', answers:['Seaweed','Lettuce','Bread','Cheese'], correct:0 },
  { cat:'Food', difficulty:'easy', text:'Which breakfast food is made from beaten eggs?', answers:['Toast','Omelet','Pancake','Muffin'], correct:1 },
  { cat:'Food', difficulty:'easy', text:'What spice is often sprinkled on rice pudding and cinnamon rolls?', answers:['Paprika','Cinnamon','Cumin','Turmeric'], correct:1 },
  { cat:'Food', difficulty:'easy', text:'What is the main ingredient in guacamole?', answers:['Tomato','Avocado','Onion','Cucumber'], correct:1 },
  { cat:'Food', difficulty:'easy', text:'Which Italian dish is made with layers of pasta, sauce, and cheese?', answers:['Risotto','Lasagna','Gnocchi','Gelato'], correct:1 },
  { cat:'Food', difficulty:'easy', text:'What type of pasta is shaped like long thin strings?', answers:['Penne','Rigatoni','Spaghetti','Fusilli'], correct:2 },
  { cat:'Food', difficulty:'easy', text:'What dairy product is churned from cream?', answers:['Yogurt','Butter','Milk','Sour cream'], correct:1 },
  { cat:'Food', difficulty:'easy', text:'Which nut is used to make marzipan?', answers:['Almond','Peanut','Walnut','Pecan'], correct:0 },
  { cat:'Food', difficulty:'easy', text:'What fast food item is often described as having all-beef patties, special sauce, lettuce, cheese, pickles, onions?', answers:['Whopper','Big Mac','Quarter Pounder','Double Stack'], correct:1 },
  { cat:'Food', difficulty:'easy', text:'What fruit is yellow and curved?', answers:['Banana','Lemon','Mango','Pineapple'], correct:0 },
  { cat:'Food', difficulty:'easy', text:'Which beverage is made by steeping tea leaves in hot water?', answers:['Coffee','Tea','Milkshake','Lemonade'], correct:1 },
  { cat:'Food', difficulty:'easy', text:'What is the main ingredient in hummus?', answers:['Black beans','Chickpeas','Lentils','Peas'], correct:1 },
  { cat:'Food', difficulty:'easy', text:'Which dessert is traditionally served on birthdays?', answers:['Pie','Cake','Pudding','Brownies'], correct:1 },
  { cat:'Food', difficulty:'easy', text:'What meat is typically used in a BLT sandwich?', answers:['Ham','Turkey','Bacon','Chicken'], correct:2 },
  { cat:'Food', difficulty:'easy', text:'Which food is known for holes and often associated with Switzerland?', answers:['Swiss cheese','Yogurt','Pretzels','Fondue'], correct:0 },
  { cat:'Food', difficulty:'easy', text:'What is the top layer of a pizza commonly called?', answers:['Crust','Sauce','Slice','Edge'], correct:0 },
  { cat:'Food', difficulty:'easy', text:'Which citrus fruit is usually orange in color and shares its name with a color?', answers:['Lemon','Lime','Orange','Grapefruit'], correct:2 },
  { cat:'Food', difficulty:'easy', text:'What do bees make that people eat?', answers:['Jam','Syrup','Honey','Butter'], correct:2 },
  { cat:'Science', difficulty:'easy', text:'What planet is known as the Red Planet?', answers:['Venus','Mars','Jupiter','Mercury'], correct:1 },
  { cat:'Science', difficulty:'easy', text:'What gas do humans breathe in to survive?', answers:['Carbon dioxide','Helium','Oxygen','Nitrogen'], correct:2 },
  { cat:'Science', difficulty:'easy', text:'How many legs does an insect have?', answers:['4','6','8','10'], correct:1 },
  { cat:'Science', difficulty:'easy', text:'What force keeps us on the ground?', answers:['Magnetism','Gravity','Friction','Pressure'], correct:1 },
  { cat:'Science', difficulty:'easy', text:'What part of the plant absorbs water from the soil?', answers:['Leaf','Stem','Root','Flower'], correct:2 },
  { cat:'Science', difficulty:'easy', text:'What is H2O commonly known as?', answers:['Salt','Hydrogen peroxide','Water','Oxygen'], correct:2 },
  { cat:'Science', difficulty:'easy', text:'Which star is at the center of our solar system?', answers:['Polaris','Sirius','The Sun','Betelgeuse'], correct:2 },
  { cat:'Science', difficulty:'easy', text:'What do caterpillars turn into?', answers:['Beetles','Butterflies','Dragonflies','Moths only'], correct:1 },
  { cat:'Science', difficulty:'easy', text:'What organ pumps blood through the body?', answers:['Brain','Liver','Heart','Lung'], correct:2 },
  { cat:'Science', difficulty:'easy', text:'What is the boiling point of water at sea level in Celsius?', answers:['50','75','100','125'], correct:2 },
  { cat:'Science', difficulty:'easy', text:'What do we call animals that eat only plants?', answers:['Carnivores','Herbivores','Omnivores','Predators'], correct:1 },
  { cat:'Science', difficulty:'easy', text:'What planet do humans live on?', answers:['Mars','Earth','Venus','Saturn'], correct:1 },
  { cat:'Science', difficulty:'easy', text:'Which part of the body helps you think?', answers:['Stomach','Liver','Brain','Kidney'], correct:2 },
  { cat:'Science', difficulty:'easy', text:'What do plants need from sunlight to make food?', answers:['Photosynthesis','Respiration','Evaporation','Digestion'], correct:0 },
  { cat:'Science', difficulty:'easy', text:'Which animal is known for changing color to blend in?', answers:['Elephant','Chameleon','Dolphin','Giraffe'], correct:1 },
  { cat:'Science', difficulty:'easy', text:'What kind of rock is formed from cooled lava?', answers:['Sedimentary','Metamorphic','Igneous','Fossil'], correct:2 },
  { cat:'Science', difficulty:'easy', text:'What is the largest planet in our solar system?', answers:['Earth','Jupiter','Saturn','Neptune'], correct:1 },
  { cat:'Science', difficulty:'easy', text:'What metal is liquid at room temperature?', answers:['Iron','Gold','Mercury','Silver'], correct:2 },
  { cat:'Science', difficulty:'easy', text:'How many bones are in the adult human body?', answers:['206','156','106','306'], correct:0 },
  { cat:'Science', difficulty:'easy', text:'What gas do plants take in from the air?', answers:['Oxygen','Hydrogen','Carbon dioxide','Helium'], correct:2 },
  { cat:'Nostalgia', difficulty:'easy', text:'What portable music player did Apple make famous in the 2000s?', answers:['Walkman','Zune','iPod','Discman'], correct:2 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which toy line featured tiny horses with colorful manes?', answers:['Care Bears','My Little Pony','Polly Pocket','Beanie Babies'], correct:1 },
  { cat:'Nostalgia', difficulty:'easy', text:'What game console was made by Nintendo and used cartridges in the 1980s?', answers:['GameCube','NES','Wii','Switch'], correct:1 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which children\'s TV show featured a big purple dinosaur named Barney?', answers:['Teletubbies','Blue\'s Clues','Barney & Friends','Sesame Street'], correct:2 },
  { cat:'Nostalgia', difficulty:'easy', text:'What toy is a colorful plastic cube puzzle invented by Ernő Rubik?', answers:['Slinky','Rubik\'s Cube','Lite-Brite','Yo-yo'], correct:1 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which handheld virtual pet needed feeding and care?', answers:['Tamagotchi','Furby','Game Boy','Bop It'], correct:0 },
  { cat:'Nostalgia', difficulty:'easy', text:'What candy is known for the slogan "Melts in your mouth, not in your hands"?', answers:['Skittles','M&M\'s','Starburst','Nerds'], correct:1 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which 90s TV show featured six friends living in New York City?', answers:['Seinfeld','Friends','Full House','Boy Meets World'], correct:1 },
  { cat:'Nostalgia', difficulty:'easy', text:'What toy spring walks down stairs?', answers:['Slinky','Stretch Armstrong','Etch A Sketch','Super Soaker'], correct:0 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which game had the phrase "You have died of dysentery"?', answers:['SimCity','The Oregon Trail','Carmen Sandiego','Lemmings'], correct:1 },
  { cat:'Nostalgia', difficulty:'easy', text:'What was the name of the talking furry toy popular in the late 1990s?', answers:['Pound Puppy','Furby','Care Bear','Glo Worm'], correct:1 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which board game asks players to solve a murder mystery?', answers:['Sorry!','Clue','Life','Risk'], correct:1 },
  { cat:'Nostalgia', difficulty:'easy', text:'What colorful peg-based toy lights up pictures?', answers:['Lite-Brite','Lincoln Logs','Tinkertoy','Spirograph'], correct:0 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which kids\' show featured a map and a backpack on adventures?', answers:['Arthur','Dora the Explorer','Rugrats','Recess'], correct:1 },
  { cat:'Nostalgia', difficulty:'easy', text:'What cassette-playing device was popular before iPods?', answers:['Walkman','Discman','MiniDisc','BoomBox'], correct:0 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which blue hedgehog video game character races through loops?', answers:['Crash Bandicoot','Mario','Sonic','Pac-Man'], correct:2 },
  { cat:'Nostalgia', difficulty:'easy', text:'What art toy lets you draw with two knobs and shake to erase?', answers:['Etch A Sketch','Lite-Brite','Magic Slate','Spirograph'], correct:0 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which 80s and 90s lunchbox favorite was a fruit drink in a foil pouch?', answers:['Capri Sun','Hi-C','SunnyD','Kool-Aid'], correct:0 },
  { cat:'Nostalgia', difficulty:'easy', text:'What educational TV series asked "Where in the world is Carmen Sandiego?"', answers:['Reading Rainbow','Wishbone','Carmen Sandiego','Zoom'], correct:2 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which toy water gun brand became huge in the 1990s?', answers:['Nerf','Water Warriors','Super Soaker','Splash Blaster'], correct:2 },
  { cat:'Pop Culture', difficulty:'medium', text:'Which actor voices Woody in the Toy Story movies?', answers:['Tom Hanks','Tim Allen','Billy Crystal','Robin Williams'], correct:0 },
  { cat:'Pop Culture', difficulty:'medium', text:'What was the first feature-length animated movie released by Disney?', answers:['Pinocchio','Fantasia','Snow White and the Seven Dwarfs','Bambi'], correct:2 },
  { cat:'Pop Culture', difficulty:'medium', text:'Which TV show features the fictional paper company Dunder Mifflin?', answers:['Parks and Recreation','The Office','30 Rock','Brooklyn Nine-Nine'], correct:1 },
  { cat:'Pop Culture', difficulty:'medium', text:'Who directed the movie Jaws?', answers:['George Lucas','James Cameron','Steven Spielberg','Martin Scorsese'], correct:2 },
  { cat:'Pop Culture', difficulty:'medium', text:'What is Lady Gaga\'s real first name?', answers:['Stefani','Joanne','Alessandra','Natalie'], correct:0 },
  { cat:'Pop Culture', difficulty:'medium', text:'In Stranger Things, what is the name of the alternate dimension?', answers:['The Dark Zone','The Underworld','The Upside Down','The Void'], correct:2 },
  { cat:'Pop Culture', difficulty:'medium', text:'Which band released the album Abbey Road?', answers:['The Rolling Stones','The Beatles','Queen','Pink Floyd'], correct:1 },
  { cat:'Pop Culture', difficulty:'medium', text:'What is the name of the coffee shop in Friends?', answers:['Coffee Central','Central Brew','Central Perk','Perk Place'], correct:2 },
  { cat:'Pop Culture', difficulty:'medium', text:'Which pop star starred in the movie The Bodyguard?', answers:['Madonna','Mariah Carey','Whitney Houston','Janet Jackson'], correct:2 },
  { cat:'Pop Culture', difficulty:'medium', text:'What fictional African country appears in Black Panther?', answers:['Genosha','Latveria','Zamunda','Wakanda'], correct:3 },
  { cat:'Sports', difficulty:'medium', text:'How many minutes are in a regulation NBA game?', answers:['40','48','50','60'], correct:1 },
  { cat:'Sports', difficulty:'medium', text:'Which country won the 2014 FIFA World Cup?', answers:['Argentina','Germany','Brazil','France'], correct:1 },
  { cat:'Sports', difficulty:'medium', text:'What is the name of the trophy awarded to the NHL champion?', answers:['Commissioner\'s Trophy','Lombardi Trophy','Stanley Cup','Larry O\'Brien Trophy'], correct:2 },
  { cat:'Sports', difficulty:'medium', text:'In baseball, how many strikes make an out?', answers:['2','3','4','5'], correct:1 },
  { cat:'Sports', difficulty:'medium', text:'Which tennis tournament is played on grass?', answers:['French Open','US Open','Australian Open','Wimbledon'], correct:3 },
  { cat:'Sports', difficulty:'medium', text:'What number did Michael Jordan famously wear for most of his NBA career?', answers:['23','24','32','45'], correct:0 },
  { cat:'Sports', difficulty:'medium', text:'In golf, what is one stroke under par called?', answers:['Eagle','Birdie','Bogey','Albatross'], correct:1 },
  { cat:'Sports', difficulty:'medium', text:'Which country hosts the Monaco Grand Prix?', answers:['Italy','Monaco','France','Spain'], correct:1 },
  { cat:'Sports', difficulty:'medium', text:'What position does a quarterback play in football?', answers:['Defense','Special teams','Offense','Goalkeeping'], correct:2 },
  { cat:'Sports', difficulty:'medium', text:'How many players are on a volleyball team on the court at once?', answers:['5','6','7','8'], correct:1 },
  { cat:'History', difficulty:'medium', text:'Who wrote the Declaration of Independence?', answers:['George Washington','Benjamin Franklin','John Hancock','Thomas Jefferson'], correct:3 },
  { cat:'History', difficulty:'medium', text:'Which civilization built the Colosseum?', answers:['Greeks','Romans','Egyptians','Persians'], correct:1 },
  { cat:'History', difficulty:'medium', text:'Who was the Soviet leader during much of World War II?', answers:['Lenin','Stalin','Trotsky','Khrushchev'], correct:1 },
  { cat:'History', difficulty:'medium', text:'What year did the United States declare independence?', answers:['1775','1776','1781','1789'], correct:1 },
  { cat:'History', difficulty:'medium', text:'Which ship carried the Pilgrims to America in 1620?', answers:['Mayflower','Santa Maria','Endeavour','Beagle'], correct:0 },
  { cat:'History', difficulty:'medium', text:'Who was assassinated in Sarajevo in 1914, helping spark World War I?', answers:['Tsar Nicholas II','Archduke Franz Ferdinand','Kaiser Wilhelm II','Otto von Bismarck'], correct:1 },
  { cat:'History', difficulty:'medium', text:'What was the name of the period of intellectual and cultural growth in Europe after the Middle Ages?', answers:['Industrial Revolution','Age of Exploration','Renaissance','Reformation'], correct:2 },
  { cat:'History', difficulty:'medium', text:'Which empire was centered in modern-day Turkey and lasted over 600 years?', answers:['Roman Empire','Ottoman Empire','Mongol Empire','Byzantine Empire'], correct:1 },
  { cat:'History', difficulty:'medium', text:'Who was the famous nurse known as the founder of modern nursing?', answers:['Clara Barton','Florence Nightingale','Mary Seacole','Dorothea Dix'], correct:1 },
  { cat:'History', difficulty:'medium', text:'What 1929 event helped trigger the Great Depression?', answers:['Boston Tea Party','Stock Market Crash','Bank of England collapse','Gold Rush'], correct:1 },
  { cat:'Food', difficulty:'medium', text:'What sauce is traditionally used in eggs Benedict?', answers:['Marinara','Hollandaise','Alfredo','Pesto'], correct:1 },
  { cat:'Food', difficulty:'medium', text:'Which country is credited with inventing pizza in its modern form?', answers:['Greece','France','Italy','United States'], correct:2 },
  { cat:'Food', difficulty:'medium', text:'What grain is the main ingredient in risotto?', answers:['Barley','Rice','Oats','Quinoa'], correct:1 },
  { cat:'Food', difficulty:'medium', text:'What kind of pastry is typically used for profiteroles?', answers:['Puff pastry','Shortcrust','Choux pastry','Phyllo dough'], correct:2 },
  { cat:'Food', difficulty:'medium', text:'What is the main protein in traditional miso soup?', answers:['Chicken','Tofu','Beef','Pork'], correct:1 },
  { cat:'Food', difficulty:'medium', text:'Which fruit is dried to make a prune?', answers:['Plum','Apricot','Peach','Date'], correct:0 },
  { cat:'Food', difficulty:'medium', text:'What Mexican dish consists of a tortilla filled and rolled around a filling, then often covered in sauce?', answers:['Taco','Burrito','Enchilada','Quesadilla'], correct:2 },
  { cat:'Food', difficulty:'medium', text:'What French term describes food cooked "under vacuum"?', answers:['Mise en place','Julienne','Sous vide','Confit'], correct:2 },
  { cat:'Food', difficulty:'medium', text:'What is the primary ingredient in traditional pesto?', answers:['Basil','Parsley','Spinach','Cilantro'], correct:0 },
  { cat:'Food', difficulty:'medium', text:'Which cheese is commonly used on a classic Greek salad?', answers:['Brie','Feta','Swiss','Provolone'], correct:1 },
  { cat:'Science', difficulty:'medium', text:'What is the chemical symbol for gold?', answers:['Ag','Au','Gd','Go'], correct:1 },
  { cat:'Science', difficulty:'medium', text:'Which planet has the most extensive ring system?', answers:['Jupiter','Saturn','Uranus','Neptune'], correct:1 },
  { cat:'Science', difficulty:'medium', text:'What is the hardest natural substance on Earth?', answers:['Iron','Diamond','Quartz','Granite'], correct:1 },
  { cat:'Science', difficulty:'medium', text:'What blood type is known as the universal donor?', answers:['AB positive','O positive','O negative','A negative'], correct:2 },
  { cat:'Science', difficulty:'medium', text:'Which part of the cell contains genetic material?', answers:['Membrane','Nucleus','Ribosome','Cytoplasm'], correct:1 },
  { cat:'Science', difficulty:'medium', text:'How long does Earth take to orbit the Sun?', answers:['24 hours','30 days','365 days','730 days'], correct:2 },
  { cat:'Science', difficulty:'medium', text:'What scientist developed the theory of general relativity?', answers:['Isaac Newton','Galileo Galilei','Albert Einstein','Nikola Tesla'], correct:2 },
  { cat:'Science', difficulty:'medium', text:'What vitamin is mainly produced when skin is exposed to sunlight?', answers:['Vitamin A','Vitamin C','Vitamin D','Vitamin K'], correct:2 },
  { cat:'Science', difficulty:'medium', text:'What is the center of an atom called?', answers:['Electron','Proton','Nucleus','Orbit'], correct:2 },
  { cat:'Science', difficulty:'medium', text:'Which organ is primarily responsible for filtering blood?', answers:['Heart','Lungs','Kidneys','Pancreas'], correct:2 },
  { cat:'Nostalgia', difficulty:'medium', text:'Which handheld console did Nintendo release in 1989?', answers:['Game Boy','Game Gear','DS','Virtual Boy'], correct:0 },
  { cat:'Nostalgia', difficulty:'medium', text:'What snack mascot was Chester Cheetah associated with?', answers:['Doritos','Cheetos','Cheez-Its','Pringles'], correct:1 },
  { cat:'Nostalgia', difficulty:'medium', text:'Which 90s sitcom starred Will Smith as a fictionalized version of himself?', answers:['Martin','Family Matters','The Fresh Prince of Bel-Air','Moesha'], correct:2 },
  { cat:'Nostalgia', difficulty:'medium', text:'What toy line featured collectible babies with pacifiers and adoption papers?', answers:['Beanie Babies','Cabbage Patch Kids','Care Bears','Polly Pocket'], correct:1 },
  { cat:'Nostalgia', difficulty:'medium', text:'Which educational computer game challenged players to track a criminal around the world?', answers:['Reader Rabbit','Carmen Sandiego','Math Blaster','Number Munchers'], correct:1 },
  { cat:'Nostalgia', difficulty:'medium', text:'Which cartoon featured Tommy, Chuckie, and Angelica?', answers:['Doug','Hey Arnold!','Rugrats','Recess'], correct:2 },
  { cat:'Nostalgia', difficulty:'medium', text:'What early internet service told users "You\'ve got mail"?', answers:['CompuServe','AOL','Netscape','Yahoo'], correct:1 },
  { cat:'Nostalgia', difficulty:'medium', text:'Which 80s toy robot transformed into vehicles and animals?', answers:['Voltron','Transformers','GoBots','Zoids'], correct:1 },
  { cat:'Nostalgia', difficulty:'medium', text:'What 90s trend involved wearing colorful rubber bracelets and slap bands?', answers:['Mood rings','Friendship pins','Gel bracelets','Slap bracelets'], correct:3 },
  { cat:'Nostalgia', difficulty:'medium', text:'Which classic arcade character eats dots and avoids ghosts?', answers:['Donkey Kong','Pac-Man','Q*bert','Frogger'], correct:1 },
];