export const generalQuestions: { cat: string; difficulty: string; text: string; answers: string[]; correct: number }[] = [
  // ─── BATCH 1 ──────────────────────────────────────────────────
  { cat:'Sports', difficulty:'easy', text:'Which sport is known as America\'s pastime?', answers:['Basketball','Baseball','Football','Hockey'], correct:1 },
  { cat:'History', difficulty:'easy', text:'Who was the first President of the United States?', answers:['Thomas Jefferson','Abraham Lincoln','George Washington','John Adams'], correct:2 },
  { cat:'Pop Culture', difficulty:'medium', text:'Which social media app is known for short dance videos and trends?', answers:['Twitter','TikTok','LinkedIn','Reddit'], correct:1 },
  { cat:'Music', difficulty:'easy', text:'Which singer is known as the "King of Pop"?', answers:['Elvis Presley','Michael Jackson','Prince','Justin Timberlake'], correct:1 },
  { cat:'Food & Drink', difficulty:'easy', text:'Which drink is made from brewed coffee beans?', answers:['Tea','Coffee','Cocoa','Lemonade'], correct:1 },
  { cat:'Movies & TV', difficulty:'easy', text:'In the movie Frozen, what is the name of the snowman?', answers:['Sven','Olaf','Kristoff','Hans'], correct:1 },
  { cat:'Geography', difficulty:'easy', text:'What is the capital city of California?', answers:['Los Angeles','San Diego','Sacramento','San Francisco'], correct:2 },
  { cat:'Nostalgia', difficulty:'medium', text:'Which handheld gaming system was hugely popular in the 1990s?', answers:['PlayStation Portable','Game Boy','Nintendo Switch','Sega Dreamcast'], correct:1 },
  { cat:'Science & Nature', difficulty:'easy', text:'What planet is closest to the Sun?', answers:['Mercury','Venus','Earth','Mars'], correct:0 },
  { cat:'Sports', difficulty:'medium', text:'How many players are on a baseball team on the field at one time?', answers:['7','8','9','10'], correct:2 },
  { cat:'History', difficulty:'medium', text:'In which year did the United States declare independence?', answers:['1776','1812','1492','1865'], correct:0 },
  { cat:'Pop Culture', difficulty:'medium', text:'Which company created the iPhone?', answers:['Microsoft','Apple','Samsung','Google'], correct:1 },
  { cat:'Music', difficulty:'medium', text:'Which band released the album "Abbey Road"?', answers:['The Rolling Stones','The Beatles','Queen','Pink Floyd'], correct:1 },
  { cat:'Food & Drink', difficulty:'easy', text:'Which fruit is said to keep the doctor away if eaten daily?', answers:['Banana','Apple','Orange','Grape'], correct:1 },
  { cat:'Movies & TV', difficulty:'medium', text:'Who played Jack in the movie Titanic?', answers:['Brad Pitt','Leonardo DiCaprio','Johnny Depp','Tom Cruise'], correct:1 },
  { cat:'Geography', difficulty:'medium', text:'Which U.S. state is known as the Sunshine State?', answers:['California','Florida','Arizona','Texas'], correct:1 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which toy brand features colorful interlocking bricks?', answers:['LEGO','Hot Wheels','Playmobil','Transformers'], correct:0 },
  { cat:'Science & Nature', difficulty:'medium', text:'What gas do humans breathe in that plants produce?', answers:['Carbon Dioxide','Nitrogen','Oxygen','Helium'], correct:2 },
  { cat:'Sports', difficulty:'hard', text:'Which country won the first FIFA World Cup in 1930?', answers:['Brazil','Germany','Uruguay','Italy'], correct:2 },
  { cat:'History', difficulty:'hard', text:'Who was the U.S. president during the Cuban Missile Crisis?', answers:['John F. Kennedy','Richard Nixon','Lyndon B. Johnson','Dwight Eisenhower'], correct:0 },
  { cat:'Pop Culture', difficulty:'easy', text:'Which fast food chain is known for the Big Mac?', answers:['Burger King','McDonald\'s','Wendy\'s','Five Guys'], correct:1 },
  { cat:'Music', difficulty:'medium', text:'Which female singer released the hit song "Rolling in the Deep"?', answers:['Adele','Beyonce','Taylor Swift','Rihanna'], correct:0 },
  { cat:'Food & Drink', difficulty:'medium', text:'What type of food is sushi traditionally made with?', answers:['Rice','Bread','Potatoes','Corn'], correct:0 },
  { cat:'Movies & TV', difficulty:'medium', text:'Which TV show features characters named Ross, Rachel, and Chandler?', answers:['Friends','Seinfeld','The Office','How I Met Your Mother'], correct:0 },
  { cat:'Geography', difficulty:'easy', text:'Which ocean borders California?', answers:['Atlantic Ocean','Pacific Ocean','Indian Ocean','Arctic Ocean'], correct:1 },
  { cat:'Nostalgia', difficulty:'medium', text:'Which 1990s cartoon featured a sponge who lives in a pineapple?', answers:['Doug','Rugrats','SpongeBob SquarePants','Hey Arnold'], correct:2 },
  { cat:'Science & Nature', difficulty:'easy', text:'What is the chemical symbol for water?', answers:['H2O','O2','CO2','NaCl'], correct:0 },
  { cat:'Sports', difficulty:'medium', text:'Which NBA player is known as "King James"?', answers:['Stephen Curry','LeBron James','Kevin Durant','Giannis Antetokounmpo'], correct:1 },
  { cat:'History', difficulty:'medium', text:'Which war was fought between the North and South regions of the United States?', answers:['World War I','Civil War','Revolutionary War','War of 1812'], correct:1 },
  { cat:'Pop Culture', difficulty:'medium', text:'Which streaming service produced the series Stranger Things?', answers:['Netflix','Hulu','Disney+','Amazon Prime'], correct:0 },
  { cat:'Music', difficulty:'easy', text:'Which instrument has black and white keys?', answers:['Guitar','Piano','Violin','Drums'], correct:1 },
  { cat:'Food & Drink', difficulty:'easy', text:'Which condiment is made from tomatoes?', answers:['Mustard','Ketchup','Mayonnaise','Relish'], correct:1 },
  { cat:'Movies & TV', difficulty:'easy', text:'What is the real name of the superhero Spider-Man?', answers:['Peter Parker','Bruce Wayne','Clark Kent','Tony Stark'], correct:0 },
  { cat:'Geography', difficulty:'medium', text:'Which country is directly north of the United States?', answers:['Mexico','Canada','Russia','Greenland'], correct:1 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which device was commonly used to rewind VHS tapes?', answers:['DVD player','VCR','Blu-ray player','MP3 player'], correct:1 },
  { cat:'Science & Nature', difficulty:'medium', text:'Which planet is known for its rings?', answers:['Mars','Saturn','Neptune','Mercury'], correct:1 },
  { cat:'Sports', difficulty:'easy', text:'How many bases are there in baseball?', answers:['3','4','5','6'], correct:1 },
  { cat:'History', difficulty:'easy', text:'Who wrote the Declaration of Independence?', answers:['Benjamin Franklin','Thomas Jefferson','George Washington','James Madison'], correct:1 },
  { cat:'Pop Culture', difficulty:'medium', text:'Which company makes the PlayStation console?', answers:['Nintendo','Sony','Microsoft','Sega'], correct:1 },
  { cat:'Music', difficulty:'hard', text:'Which composer wrote the famous Fifth Symphony?', answers:['Mozart','Bach','Beethoven','Chopin'], correct:2 },
  { cat:'Food & Drink', difficulty:'medium', text:'Which country is famous for inventing pizza?', answers:['France','Italy','Spain','Greece'], correct:1 },
  { cat:'Movies & TV', difficulty:'medium', text:'Which actor played Iron Man in the Marvel films?', answers:['Chris Evans','Robert Downey Jr.','Mark Ruffalo','Chris Hemsworth'], correct:1 },
  { cat:'Geography', difficulty:'easy', text:'What is the capital of Texas?', answers:['Houston','Austin','Dallas','San Antonio'], correct:1 },
  { cat:'Nostalgia', difficulty:'medium', text:'Which toy became a craze in the 1990s as a digital pet?', answers:['Tamagotchi','Furby','Beanie Babies','Game Boy'], correct:0 },
  { cat:'Science & Nature', difficulty:'easy', text:'Which animal is known as the largest mammal on Earth?', answers:['Elephant','Blue Whale','Giraffe','Great White Shark'], correct:1 },

  // ─── BATCH 2 ──────────────────────────────────────────────────
  { cat:'Sports', difficulty:'easy', text:'How many quarters are played in an NFL football game?', answers:['2','3','4','5'], correct:2 },
  { cat:'History', difficulty:'medium', text:'Which document begins with the words "We the People"?', answers:['Declaration of Independence','Bill of Rights','U.S. Constitution','Emancipation Proclamation'], correct:2 },
  { cat:'Pop Culture', difficulty:'easy', text:'Which fast food chain is famous for its Frosty dessert?', answers:['McDonald\'s','Wendy\'s','Burger King','Arby\'s'], correct:1 },
  { cat:'Music', difficulty:'medium', text:'Which artist released the album "Thriller"?', answers:['Prince','Michael Jackson','Madonna','Whitney Houston'], correct:1 },
  { cat:'Food & Drink', difficulty:'easy', text:'Which breakfast cereal mascot is a tiger named Tony?', answers:['Frosted Flakes','Cheerios','Lucky Charms','Corn Pops'], correct:0 },
  { cat:'Movies & TV', difficulty:'easy', text:'Who is the main character of the Harry Potter series?', answers:['Ron Weasley','Harry Potter','Draco Malfoy','Neville Longbottom'], correct:1 },
  { cat:'Geography', difficulty:'easy', text:'Which U.S. state is known as the Lone Star State?', answers:['Texas','Arizona','Nevada','Oklahoma'], correct:0 },
  { cat:'Nostalgia', difficulty:'medium', text:'Which video game character collects rings and runs very fast?', answers:['Mario','Sonic','Link','Crash'], correct:1 },
  { cat:'Science & Nature', difficulty:'easy', text:'What part of a plant conducts photosynthesis?', answers:['Root','Stem','Leaf','Seed'], correct:2 },
  { cat:'Sports', difficulty:'medium', text:'In basketball how many points is a three-point shot worth?', answers:['1','2','3','4'], correct:2 },
  { cat:'History', difficulty:'easy', text:'Who was the 16th President of the United States?', answers:['Abraham Lincoln','Andrew Jackson','Ulysses Grant','James Polk'], correct:0 },
  { cat:'Pop Culture', difficulty:'medium', text:'Which company created the streaming platform Disney+?', answers:['Warner Bros.','Disney','NBC','Sony'], correct:1 },
  { cat:'Music', difficulty:'easy', text:'Which instrument is commonly associated with country music?', answers:['Banjo','Flute','Cello','Oboe'], correct:0 },
  { cat:'Food & Drink', difficulty:'medium', text:'Which nut is used to make traditional pesto sauce?', answers:['Peanut','Pine Nut','Walnut','Almond'], correct:1 },
  { cat:'Movies & TV', difficulty:'medium', text:'Which actor voiced Woody in Toy Story?', answers:['Tim Allen','Tom Hanks','Robin Williams','Billy Crystal'], correct:1 },
  { cat:'Geography', difficulty:'medium', text:'Which Great Lake borders Chicago?', answers:['Lake Superior','Lake Michigan','Lake Erie','Lake Ontario'], correct:1 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which board game features properties like Boardwalk and Park Place?', answers:['Clue','Monopoly','Risk','Life'], correct:1 },
  { cat:'Science & Nature', difficulty:'medium', text:'What force pulls objects toward Earth?', answers:['Magnetism','Gravity','Friction','Electricity'], correct:1 },
  { cat:'Sports', difficulty:'medium', text:'Which sport uses a puck?', answers:['Hockey','Lacrosse','Cricket','Rugby'], correct:0 },
  { cat:'History', difficulty:'medium', text:'Which U.S. president was nicknamed "Teddy"?', answers:['Franklin Roosevelt','Theodore Roosevelt','Woodrow Wilson','Calvin Coolidge'], correct:1 },
  { cat:'Pop Culture', difficulty:'easy', text:'Which toy cowboy is a main character in Toy Story?', answers:['Buzz','Woody','Jessie','Rex'], correct:1 },
  { cat:'Music', difficulty:'medium', text:'Which singer released the hit "Shake It Off"?', answers:['Adele','Taylor Swift','Lady Gaga','Katy Perry'], correct:1 },
  { cat:'Food & Drink', difficulty:'easy', text:'What sweet food do bees produce?', answers:['Honey','Sugar','Syrup','Molasses'], correct:0 },
  { cat:'Movies & TV', difficulty:'easy', text:'Which superhero is known as the Caped Crusader?', answers:['Superman','Batman','Iron Man','Spider-Man'], correct:1 },
  { cat:'Geography', difficulty:'easy', text:'Which continent is the United States located on?', answers:['Europe','Asia','North America','South America'], correct:2 },
  { cat:'Nostalgia', difficulty:'medium', text:'Which 1980s arcade game features a yellow character eating pellets?', answers:['Donkey Kong','Pac-Man','Galaga','Frogger'], correct:1 },
  { cat:'Science & Nature', difficulty:'medium', text:'What gas do plants absorb from the air?', answers:['Oxygen','Carbon Dioxide','Nitrogen','Helium'], correct:1 },
  { cat:'Sports', difficulty:'hard', text:'Which tennis tournament is played on grass courts?', answers:['US Open','French Open','Wimbledon','Australian Open'], correct:2 },
  { cat:'History', difficulty:'hard', text:'Which ship carried the Pilgrims to America in 1620?', answers:['Santa Maria','Mayflower','Endeavour','Discovery'], correct:1 },
  { cat:'Pop Culture', difficulty:'medium', text:'Which company produces the video game series Halo?', answers:['Nintendo','Microsoft','Sony','Valve'], correct:1 },
  { cat:'Music', difficulty:'medium', text:'Which singer was known as the "Queen of Soul"?', answers:['Whitney Houston','Aretha Franklin','Tina Turner','Diana Ross'], correct:1 },
  { cat:'Food & Drink', difficulty:'medium', text:'Which fruit is the main ingredient in guacamole?', answers:['Avocado','Tomato','Mango','Papaya'], correct:0 },
  { cat:'Movies & TV', difficulty:'medium', text:'Which fictional town is home to the Simpson family?', answers:['Shelbyville','Springfield','Quahog','South Park'], correct:1 },
  { cat:'Geography', difficulty:'medium', text:'Which country has the city of Sydney?', answers:['Canada','Australia','New Zealand','United Kingdom'], correct:1 },
  { cat:'Nostalgia', difficulty:'easy', text:'Which toy vehicle brand is famous for small die-cast cars?', answers:['Matchbox','Hot Wheels','Tonka','Fisher-Price'], correct:1 },
  { cat:'Science & Nature', difficulty:'easy', text:'How many legs does a spider have?', answers:['6','8','10','12'], correct:1 },
  { cat:'Sports', difficulty:'easy', text:'Which sport uses a bat and ball and has nine innings?', answers:['Baseball','Soccer','Basketball','Hockey'], correct:0 },
  { cat:'History', difficulty:'medium', text:'Which amendment ended slavery in the United States?', answers:['10th','13th','15th','19th'], correct:1 },
  { cat:'Pop Culture', difficulty:'medium', text:'Which animated series features characters named Stan, Kyle, Cartman, and Kenny?', answers:['Family Guy','South Park','Futurama','Rick and Morty'], correct:1 },
  { cat:'Music', difficulty:'hard', text:'Which band released the song "Bohemian Rhapsody"?', answers:['Queen','The Who','Led Zeppelin','The Beatles'], correct:0 },
  { cat:'Food & Drink', difficulty:'easy', text:'Which dairy product is used to make butter?', answers:['Milk','Cream','Yogurt','Ice Cream'], correct:1 },
  { cat:'Movies & TV', difficulty:'medium', text:'Which character famously says "May the Force be with you" in Star Wars?', answers:['Luke Skywalker','Yoda','Obi-Wan Kenobi','Han Solo'], correct:2 },
  { cat:'Geography', difficulty:'medium', text:'Which desert covers much of northern Africa?', answers:['Gobi','Sahara','Kalahari','Mojave'], correct:1 },
  { cat:'Nostalgia', difficulty:'medium', text:'Which 90s handheld toy let kids care for a digital pet?', answers:['Furby','Tamagotchi','Game Boy','Talkboy'], correct:1 },
  { cat:'Science & Nature', difficulty:'medium', text:'What organ helps humans breathe?', answers:['Heart','Lungs','Kidneys','Liver'], correct:1 },
  { cat:'Sports', difficulty:'medium', text:'Which country hosts the Tour de France cycling race?', answers:['Italy','France','Spain','Belgium'], correct:1 },
  { cat:'History', difficulty:'medium', text:'Which U.S. president appears on the $1 bill?', answers:['George Washington','Thomas Jefferson','Andrew Jackson','Benjamin Franklin'], correct:0 },
  { cat:'Pop Culture', difficulty:'easy', text:'Which animated mouse is the mascot of Disney?', answers:['Jerry','Mickey Mouse','Stuart Little','Speedy Gonzales'], correct:1 },
  { cat:'Music', difficulty:'easy', text:'Which instrument is played with drumsticks?', answers:['Guitar','Drums','Piano','Trumpet'], correct:1 },
  { cat:'Food & Drink', difficulty:'medium', text:'Which Italian dish is made with layers of pasta, cheese, and sauce?', answers:['Lasagna','Risotto','Gnocchi','Fettuccine'], correct:0 },
  { cat:'Movies & TV', difficulty:'easy', text:'Which animated movie features a talking snowman named Olaf?', answers:['Frozen','Moana','Encanto','Tangled'], correct:0 },
  { cat:'Geography', difficulty:'hard', text:'Which river is the longest in the United States?', answers:['Mississippi River','Missouri River','Colorado River','Rio Grande'], correct:0 },
  { cat:'Nostalgia', difficulty:'medium', text:'Which 90s TV show featured teenagers morphing into the Power Rangers?', answers:['VR Troopers','Mighty Morphin Power Rangers','Beetleborgs','Masked Rider'], correct:1 },
  { cat:'Science & Nature', difficulty:'hard', text:'What is the hardest natural substance on Earth?', answers:['Iron','Diamond','Quartz','Granite'], correct:1 },
];
