export const pittsburghQuestions: { cat: string; difficulty: string; text: string; answers: string[]; correct: number }[] = [
  // ─── EASY ────────────────────────────────────────────────────
  { cat:'Pittsburgh', difficulty:'easy', text:'Which NFL team represents Pittsburgh?', answers:['Cleveland Browns','Pittsburgh Steelers','Baltimore Ravens','Cincinnati Bengals'], correct:1 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Which famous Pittsburgh amusement park features the roller coaster Phantom\'s Revenge?', answers:['Idlewild','Kennywood','Hersheypark','Cedar Point'], correct:1 },
  { cat:'Pittsburgh', difficulty:'easy', text:'What river meets the Monongahela and Allegheny Rivers at Pittsburgh\'s Point State Park?', answers:['Ohio River','Susquehanna River','Youghiogheny River','Beaver River'], correct:0 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Which Pittsburgh sandwich shop is known for putting fries inside the sandwich?', answers:['Subway','Primanti Bros.','Jersey Mike\'s','Jimmy John\'s'], correct:1 },
  { cat:'Pittsburgh', difficulty:'easy', text:'What MLB team plays at PNC Park in Pittsburgh?', answers:['Pittsburgh Pirates','Philadelphia Phillies','Detroit Tigers','Cleveland Guardians'], correct:0 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Fort Pitt was originally built during which war?', answers:['Civil War','French and Indian War','World War I','War of 1812'], correct:1 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Which county is Pittsburgh located in?', answers:['Westmoreland County','Butler County','Allegheny County','Fayette County'], correct:2 },
  { cat:'Pittsburgh', difficulty:'easy', text:'What color towels do Steelers fans wave at games?', answers:['Red','Yellow','Black','White'], correct:1 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Which Western Pennsylvania city is famous for the banana split invention claim?', answers:['Latrobe','Greensburg','Jeannette','Irwin'], correct:0 },
  { cat:'Pittsburgh', difficulty:'easy', text:'What Pittsburgh incline offers views from Mount Washington?', answers:['Monongahela Incline','Liberty Incline','Riverfront Lift','Steel Incline'], correct:0 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Which hockey team plays at PPG Paints Arena?', answers:['Philadelphia Flyers','Pittsburgh Penguins','Buffalo Sabres','Detroit Red Wings'], correct:1 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Which mountain region east of Pittsburgh includes Ohiopyle State Park?', answers:['Laurel Highlands','Blue Ridge Mountains','Catskills','Adirondacks'], correct:0 },
  { cat:'Pittsburgh', difficulty:'easy', text:'What nickname is commonly used for Pittsburgh residents?', answers:['Yinzers','Buckeyes','Hilltoppers','Keystoners'], correct:0 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Which historic amusement park is located in West Mifflin?', answers:['Kennywood','Idlewild','Waldameer','DelGrosso\'s'], correct:0 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Which famous brewery started in Latrobe, Pennsylvania?', answers:['Yuengling','Rolling Rock','Samuel Adams','Coors'], correct:1 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Which Pittsburgh quarterback led the Steelers to two Super Bowl wins in the 2000s?', answers:['Ben Roethlisberger','Terry Bradshaw','Neil O\'Donnell','Tommy Maddox'], correct:0 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Which river runs through Ohiopyle State Park?', answers:['Allegheny River','Youghiogheny River','Ohio River','Clarion River'], correct:1 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Which park in downtown Pittsburgh sits where three rivers meet?', answers:['Point State Park','Schenley Park','Frick Park','Highland Park'], correct:0 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Which Pittsburgh neighborhood is famous for its steep hills and city views?', answers:['Oakland','Mount Washington','Shadyside','Bloomfield'], correct:1 },
  { cat:'Pittsburgh', difficulty:'easy', text:'Which stadium did the Steelers play in before Acrisure Stadium?', answers:['Heinz Field','Three Rivers Stadium','Forbes Field','PNC Park'], correct:0 },

  // ─── MEDIUM ──────────────────────────────────────────────────
  { cat:'Pittsburgh', difficulty:'medium', text:'Which industrialist founded Carnegie Mellon University?', answers:['Andrew Carnegie','Henry Clay Frick','John Heinz','George Westinghouse'], correct:0 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which historic site near Ligonier recreates a British fort from the 1700s?', answers:['Fort Pitt Museum','Fort Necessity','Fort Ligonier','Fort Bedford'], correct:2 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which Pittsburgh Pirates player famously hit a home run in Game 7 of the 1960 World Series?', answers:['Roberto Clemente','Bill Mazeroski','Willie Stargell','Dave Parker'], correct:1 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which candy company was founded in Pittsburgh in 1894?', answers:['Mars','Hershey','Clark Bar','Cadbury'], correct:2 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which suburb east of Pittsburgh is known for the Monroeville Mall?', answers:['Greensburg','Monroeville','Irwin','Latrobe'], correct:1 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which Pittsburgh-born pop artist created the famous Campbell\'s Soup paintings?', answers:['Andy Warhol','Roy Lichtenstein','Keith Haring','Jackson Pollock'], correct:0 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which Western Pennsylvania golfer won the 1960 U.S. Open?', answers:['Arnold Palmer','Jack Nicklaus','Tom Watson','Gary Player'], correct:0 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which steel company dominated Pittsburgh industry in the early 1900s?', answers:['U.S. Steel','Bethlehem Steel','Republic Steel','Armco'], correct:0 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which Pittsburgh bridge is known as the "Bridge of Sighs"?', answers:['Hot Metal Bridge','Roberto Clemente Bridge','Smithfield Street Bridge','Panhandle Bridge'], correct:3 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which famous Pittsburgh condiment company produces ketchup?', answers:['Heinz','Hunt\'s','Del Monte','French\'s'], correct:0 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which Western Pennsylvania county contains Greensburg?', answers:['Allegheny County','Westmoreland County','Fayette County','Butler County'], correct:1 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which Pittsburgh museum is dedicated to the work of Andy Warhol?', answers:['Warhol Museum','Carnegie Museum','Frick Museum','Mattress Factory'], correct:0 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which Pittsburgh Penguins star wore jersey number 66?', answers:['Mario Lemieux','Sidney Crosby','Jaromir Jagr','Evgeni Malkin'], correct:0 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which battle near present-day Uniontown was fought in 1754?', answers:['Battle of Jumonville Glen','Battle of Gettysburg','Battle of Yorktown','Battle of Lake Erie'], correct:0 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which state park near Pittsburgh is known for waterfalls and whitewater rafting?', answers:['Cook Forest','Ohiopyle','Raccoon Creek','Moraine'], correct:1 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which Pittsburgh neighborhood is known for its Italian heritage?', answers:['Bloomfield','Lawrenceville','Oakland','Squirrel Hill'], correct:0 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which Pittsburgh stadium hosted both the Steelers and Pirates before PNC Park?', answers:['Heinz Field','Three Rivers Stadium','Forbes Field','Civic Arena'], correct:1 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which Pittsburgh park contains the Carnegie Museums?', answers:['Frick Park','Schenley Park','Highland Park','Riverview Park'], correct:1 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which Western Pennsylvania food festival celebrates Italian heritage each summer?', answers:['Picklesburgh','Little Italy Days','Arts Festival','Banana Split Festival'], correct:1 },
  { cat:'Pittsburgh', difficulty:'medium', text:'Which Pittsburgh philanthropist funded many libraries across America?', answers:['Andrew Carnegie','Henry Clay Frick','George Westinghouse','Andrew Mellon'], correct:0 },

  // ─── HARD ────────────────────────────────────────────────────
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Western Pennsylvania industrialist co-founded Standard Oil with John D. Rockefeller?', answers:['Andrew Mellon','Henry Flagler','Henry Clay Frick','George Westinghouse'], correct:1 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which river forms part of the border between Fayette County and Somerset County?', answers:['Monongahela River','Youghiogheny River','Ohio River','Clarion River'], correct:1 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Pittsburgh Pirate won the National League MVP in 1979?', answers:['Willie Stargell','Dave Parker','Barry Bonds','Roberto Clemente'], correct:0 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Pittsburgh bridge was the first self-anchored suspension bridge in the U.S.?', answers:['Roberto Clemente Bridge','Fort Pitt Bridge','Smithfield Street Bridge','Hot Metal Bridge'], correct:1 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Pittsburgh filmmaker directed the original "Night of the Living Dead"?', answers:['George Romero','Steven Spielberg','John Carpenter','Wes Craven'], correct:0 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Pittsburgh-born chef hosted the Food Network show "30 Minute Meals"?', answers:['Rachael Ray','Ina Garten','Giada De Laurentiis','Sandra Lee'], correct:0 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Western Pennsylvania town was once called "Little Boston" for its steel industry?', answers:['Braddock','Jeannette','McKeesport','Duquesne'], correct:0 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Allegheny County park contains the historic Allegheny Observatory?', answers:['Riverview Park','Frick Park','Schenley Park','Highland Park'], correct:0 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Steelers player caught the game-winning touchdown in Super Bowl XLIII?', answers:['Hines Ward','Antonio Brown','Santonio Holmes','Heath Miller'], correct:2 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Pittsburgh neighborhood is home to the historic Carrie Blast Furnaces?', answers:['Rankin','Homestead','Braddock','Swissvale'], correct:0 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Western Pennsylvania fort was built by George Washington in 1754?', answers:['Fort Pitt','Fort Necessity','Fort Ligonier','Fort Duquesne'], correct:1 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Western Pennsylvania lake was created by the Kinzua Dam?', answers:['Lake Arthur','Allegheny Reservoir','Raystown Lake','Deep Creek Lake'], correct:1 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Penguins coach led the team to the 2009 Stanley Cup?', answers:['Dan Bylsma','Mike Sullivan','Michel Therrien','Eddie Johnston'], correct:0 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which historic Pittsburgh building was once the tallest in the world outside New York?', answers:['Cathedral of Learning','U.S. Steel Tower','Gulf Tower','Grant Building'], correct:0 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Pittsburgh company originally produced the Clark Bar candy?', answers:['Necco','Clark Company','Mars','Hershey'], correct:1 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Pittsburgh-born actor starred as Michael Scott in "The Office"?', answers:['Steve Carell','Rainn Wilson','John Krasinski','Ed Helms'], correct:0 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Pittsburgh banker helped finance the creation of the Federal Reserve System?', answers:['Andrew Mellon','Henry Clay Frick','George Westinghouse','Thomas Mellon'], correct:3 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which Allegheny County borough shares a name with a famous Pittsburgh sandwich topping?', answers:['Swissvale','Homestead','Carnegie','Bethel Park'], correct:0 },
  { cat:'Pittsburgh', difficulty:'hard', text:'Which historic Pittsburgh incline first opened in 1877?', answers:['Monongahela Incline','Duquesne Incline','Liberty Incline','Mount Washington Lift'], correct:1 },
];
